Feature/real time ais
LSTS/ripples pull request #9
Opened 2020-10-20 11:54 UTC by RicardoAndreSantos

Ais real time updates.

2020-10-20 17:22 UTC, zepinto requested changes
Please check the comments inline.

2020-10-20 17:22 UTC, zepinto commented on src/main/java/pt/lsts/ripples/controllers/WebSocketsController.java
> -        // logger.info("Broadcasting update for asset " + asset.getName());
Please remove commented code.

2020-10-20 17:22 UTC, zepinto commented on src/main/java/pt/lsts/ripples/controllers/NeptusController.java
> +public class NeptusController {
Is this controller being used? if not it should not be part of the pull request.

2020-10-20 17:22 UTC, zepinto commented on src/main/java/pt/lsts/ripples/services/AisFetcherService.java
> +    @Value("${udp.port}")
Please provide a default value (https://www.baeldung.com/spring-value-defaults).

2020-10-20 17:22 UTC, zepinto commented on src/main/java/pt/lsts/ripples/services/AisFetcherService.java
> +        logger.info("Started UPD listener on port: " + port);
Typo in UDP.

2020-10-20 17:22 UTC, zepinto commented on src/main/java/pt/lsts/ripples/services/AisFetcherService.java
> +    public class UdpListenner implements Runnable {
Class name has a typo (UdpListenner -> UDPListener)

2020-10-21 08:43 UTC, RicardoAndreSantos commented on src/main/java/pt/lsts/ripples/controllers/NeptusController.java
> +public class NeptusController {
Not yet, it was just an experience for the communication with Neptus.

2020-10-21 09:27 UTC, zepinto commented on src/main/java/pt/lsts/ripples/controllers/WebSocketsController.java
> -	// the business logic can call this to update all connected clients
Documentation is welcome. Just asked to remove the commented out code.

2020-10-21 09:28 UTC, zepinto approved these changes

2020-10-21 09:28 UTC, merged